<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Per bulan_mami-radio-icon</name>
   <tag></tag>
   <elementGuidId>f8f67148-7c29-4635-a480-d490bf22eec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mami-radio-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='priceCard']/div/section/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mami-radio-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priceCard&quot;)/div[@class=&quot;booking-card&quot;]/section[@class=&quot;booking-card__info&quot;]/div[@class=&quot;booking-card__info-select&quot;]/div[@class=&quot;booking-rent-type --open&quot;]/div[@class=&quot;booking-rent-type__options&quot;]/div[@class=&quot;booking-rent-type__options-item&quot;]/div[@class=&quot;mami-radio&quot;]/div[@class=&quot;mami-radio-icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='priceCard']/div/section/div[2]/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/section/div[2]/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
