<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdownper</name>
   <tag></tag>
   <elementGuidId>029b6b05-c111-4e45-b912-f8b5e145c71a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//INPUT[@data-v-dad62a8c='']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
